"""add ordinal to category

Revision ID: 3ee936487af0
Revises: 6a34e2646682
Create Date: 2022-05-21 14:58:59.816367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee936487af0'
down_revision = '6a34e2646682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('ordinal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'ordinal')
    # ### end Alembic commands ###
