"""add leaderboard columns to user

Revision ID: 69d885fef85b
Revises: 75e6f4df5bf9
Create Date: 2022-04-27 22:08:37.449316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d885fef85b'
down_revision = '75e6f4df5bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('leaderboard_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('level_string', sa.String(), nullable=True))
    op.add_column('user', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'score')
    op.drop_column('user', 'level_string')
    op.drop_column('user', 'leaderboard_name')
    # ### end Alembic commands ###
