"""removed extra role, added with link, username and password

Revision ID: 75e6f4df5bf9
Revises: be218b5ed4d6
Create Date: 2022-02-28 19:49:34.663690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e6f4df5bf9'
down_revision = 'be218b5ed4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('link', sa.String(), nullable=True))
    op.add_column('level', sa.Column('username', sa.String(), nullable=True))
    op.add_column('level', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('level', 'extra_discord_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('extra_discord_role', sa.VARCHAR(length=18), nullable=True))
    op.drop_column('level', 'password')
    op.drop_column('level', 'username')
    op.drop_column('level', 'link')
    # ### end Alembic commands ###
