"""init

Revision ID: be218b5ed4d6
Revises: 
Create Date: 2022-02-13 21:24:18.895999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be218b5ed4d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('discord_category', sa.String(length=20), nullable=True),
    sa.Column('colour', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('nick', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nickname_suffix', sa.String(), nullable=True),
    sa.Column('nickname_merge', sa.Boolean(), nullable=True),
    sa.Column('discord_channel', sa.String(length=20), nullable=True),
    sa.Column('discord_role', sa.String(length=20), nullable=True),
    sa.Column('extra_discord_role', sa.String(length=20), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('grid_x', sa.Integer(), nullable=True),
    sa.Column('grid_y', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_discord_channel'), 'level', ['discord_channel'], unique=False)
    op.create_table('prerequisite_level',
    sa.Column('parent_level', sa.String(length=36), nullable=False),
    sa.Column('child_level', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['child_level'], ['level.id'], ),
    sa.ForeignKeyConstraint(['parent_level'], ['level.id'], ),
    sa.PrimaryKeyConstraint('parent_level', 'child_level')
    )
    op.create_table('solution',
    sa.Column('level_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('level_id', 'text')
    )
    op.create_index(op.f('ix_solution_text'), 'solution', ['text'], unique=False)
    op.create_table('unlock',
    sa.Column('level_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('level_id', 'text')
    )
    op.create_index(op.f('ix_unlock_text'), 'unlock', ['text'], unique=False)
    op.create_table('user_solve',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('level_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'level_id')
    )
    op.create_table('user_unlock',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('level_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'level_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_unlock')
    op.drop_table('user_solve')
    op.drop_index(op.f('ix_unlock_text'), table_name='unlock')
    op.drop_table('unlock')
    op.drop_index(op.f('ix_solution_text'), table_name='solution')
    op.drop_table('solution')
    op.drop_table('prerequisite_level')
    op.drop_index(op.f('ix_level_discord_channel'), table_name='level')
    op.drop_table('level')
    op.drop_table('user')
    op.drop_table('setting')
    op.drop_table('category')
    # ### end Alembic commands ###
